var json_default = {

dares: [
'1. Cock reveal',
'2. Waterboarding',
'3. Kiss one of the boys',
'4. AMA (on video confession)',
'5. Geoguesser',
'6. Music video / Movie scene re-enactment',
'7. Karaoke Solo',
'8. Freestyle / Pokernight poem',
'9. Round of rhymes (strict) / Round of categories / Round of associations (fast)',
'10. Give a genuine compliment/ last dare',
'11. Playlist quiz 5 songs',
'12. Tape Hands and Legs / Mouth and Chair 10 min',
'13. Bare back slap / Roundhouse kick / Neck tap',
'14. Karaoke Duet',
'15. Balancing 1v1 w/last drink',
'16. Slap to the face / Ass slap round',
'17. Show the boys a dance move, they need to replicate',
'18. Back to Back most likely to finish drink / Who Knows Who w/last dare',
'19. 1 min plank / wall sit',
'20. Rap battle / Poem 1v1 - Call out anyone',
'21. Karaoke Full Gang',
'22. Categories 1v1 w/last drink',
'23. Odds on - Russian Roulette Version',
'24. Piirrä donnie 1 min',
'25. Vaihda housuja / Strip down with a homie for 6m w/last drink',
'26. Spelling bee ENG FRA GER (coinflip) / Tongue Twister',
'27. Staring contest & Associoation 1v1 /last drink', 
'28. New song recommendation, presented with Karaoke',
'29. Tug of War / Arm Wrestle / Thumb War 1v1 w/last drink',
'30. Join the next dare',
'31. Situps, pushups, squats 10x15sec',
'32. Guess Who 1v1 (PotC/SW/LotR)',
'33. Kiss / Hug something for a good picture', 
'34. Show the boys your favourite Anime / Movie scene & Explain why its so good',
'35. Yöton Yö scene w/last drink', 
'36. Pukkihyppy down the hall w/last drink',
'37. Kanna donnie reppuselässä / Pic of you holding a donnie  w/last drink', 
'38. Traumadump / Valid Crashout',
'39. Showcase a special talent',
'40. Lick doorknob / Eat some leaves',
'41. Confession Wheel',
'100. Round of Shots',
],

wheel_changes: [
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Box of Memes',
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [
"#E74C3C",
"#7D3C98",
"#2E86C1",
"#138D75",
"#F1C40F",
"#D35400",
"#138D75",
"#F1C40F",
"#b163da",
"#E74C3C",
"#7D3C98",
"#138D75",
]

};