var json_no_sitting = {

dares: [
'1. Cock reveal',
'2. Hop in trash',
'3. Ice shower 20 sec / Take a swin (Lohja/Teisko)',
'6. Tug of war käsillä/ last drink',
'8. Waterboarding',
'9. Roundhouse kick',
'11. Situps, pushups, squats 10x 15sec',
'12. Talon ympäri 20 secs',
'13. Run it down luoteisväylä (no pants/shirt)',
'15. Music video',
'17. Join the next dare',
'19. Talon katolle',
'22. Slap to the face',
'23. Ass slap round',
'24. Breath holding /last dare',
'26. 1v1 kädenvääntö/ last drink',
'27. Crab walk',
'30. Shamone',
'31. Round of shots',
'33. Freestyle',
'35. Three shots 1 water 2 vergi',
'36. 5 second challenge',
'37. 50/50 shot tai kaikki muut shottaa',
'39. Playlist quiz 5 songs',
'40. Karaoke',
'41. Movie scene/porn scene',
'44. Bare back slap',
'46. Odds on/ last dare',
'47. Walk a straight a line / Walk the plank (Lohja/Teisko)',
'52. Round of shots',
'53. 50/50 3 pieces tai shot',
'54. Blitz round 1 min',
'56. 50/50 2 shots tai free pass',
'59. RPS for a shot anyone',
'63. Secret banned category',
'64. Charades (15 correct in custom)',
'65. 1 min plank / wall sit',
'69. Make a cocktail with onhand ingredients, choose a donnie to taste test',
'72. Round of shots',
'73. Categories 1v1/ last drink',
'74. Thumb war/ last drink',
'75. Back to Back most likely to finish drink /last dare',
'77. Rap battle/ call out',
'78. Show the boys a dance move',
'81. Association test',
'84. Dishwashing liquid 20 sec',
'86. Vaihda housuja 10m/ last drink',
'87. Cartwheel / handstand / ukemi',
'88. Blindfolded outside',
'89. BENCH PRESS MAX OUT',
'91. Try not to laugh',
'92. Round of shots',
'93. Forced shotbuddies',
'94. Tape hand and legs 10min',
'96. Neck tap',
'99. Ala Habibi Resurrected',
'100. Bet on one of the guys (W/ Drink | L/ No Drink | Shot/ Double it & Drink)',
'101. 1 Glass Shot Pong',
'103. New rule until tower falls',
'104. Whos most likely to',
'105. Balancing 1v1/ last drink'
],

wheel_changes: [
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho'
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [ 
'#213e1b',
'#5e4e2e',
'#000000',
'#2d4936',
'#4b4127'
]

};