var json_default = {

dares: [
'1. Cock reveal',
'2. Hop in trash',
'3. Ice shower 20 sec / Take a swin (Lohja/Teisko)',
'4. 10 min 3 layers',
'5. Never have I ever joka gettaa kaikki',
'6. Tug of war käsillä/ last drink',
'7. Heel to toe/ last dare',
'8. Waterboarding',
'9. Roundhouse kick',
'10. Next piece & dare blindfolded',
'11. Situps, pushups, squats 10x 15sec',
'12. Talon ympäri 20 secs',
'13. Run it down luoteisväylä (no pants/shirt)',
'14. Animal noises',
'15. Music video',
'16. Lick doorknob / Match on tongue',
'17. Join the next dare',
'18. 2 mins gay porn',
'19. Talon katolle',
'20. Round of shots',
'21. WhatsApp 3 words',
'22. Slap to the face',
'23. Ass slap round',
'24. Breath holding /last dare',
'25. Kiss one of the boys',
'26. 1v1 kädenvääntö/ last drink',
'27. Crab walk',
'28. Dodgy accent & impression / Puhu takaperin 4 Min',
'29. Staring contest/ last drink',
'30. Shamone',
'31. Round of shots',
'32. AMA',
'33. Freestyle',
'34. Confession: idol / person you despise / wierd thing youve done alone',
'35. Three shots 1 water 2 vergi',
'36. 5-second challenge ',
'37. 50/50 shot tai kaikki muut shottaa',
'38. Unknown reference',
'39. Playlist quiz 5 songs',
'40. Karaoke',
'41. Movie scene/porn scene',
'42. Round of shots',
'43. Confession : Dream meal / journal page / mikä character sarjasta on you / bucket list thing',
'44. Bare back slap',
'45. Piirrä donnie 1 min',
'46. Odds on/ last dare',
'47. Walk a straight a line / Walk the plank (Lohja/Teisko)',
'48. Tell us something you hate about yourself / Narcissism 3 things 5 sec',
'49. Who wants to be a mentalist',
'50. Puhu referenceillä 3 min',
'51. Geoguesser',
'52. Round of shots',
'53. 50/50 3 pieces tai shot',
'54. Blitz round 1 min',
'55. Make a new identity / create a religion',
'56. 50/50 2 shots tai free pass',
'57. Confession: non-pornstar johon oot nutannu / fictional character youd bang',
'58. Confession: kink / favourite porn plot / most or least favourite cliche / favourite porn video',
'59. RPS for a shot anyone',
'61. Original reference',
'62. Round of shots',
'63. Secret banned category',
'64. Charades (15 correct in custom)',
'65. 1 min plank / wall sit',
'66. Draw a 3-panel comic',
'67. Round of associations',
'68. Round of rhymes',
'69. Make a cocktail with onhand ingredients, choose a donnie to taste test',
'70. Spelling bee ENG FRA GER',
'71. Descriptions',
'72. Round of shots',
'73. Categories 1v1/ last drink',
'74. Thumb war/ last drink',
'75. Back to Back most likely to finish drink /last dare',
'76. 2 truths 1 lie',
'77. Rap battle/ call out',
'78. Show the boys a dance move',
'79. Minkä fictional characterin elämän haluaisit / minkä fictional characterin kanssa voisit olla friends',
'80. 2 free pass then forced dare',
'81. Association test',
'82. Round of shots',
'83. Confession: bad person moment / pervy thing / spirit animal',
'84. Dishwashing liquid 20 sec',
'85. Tongue twister',
'86. Vaihda housuja 10m/ last drink',
'87. Cartwheel / handstand / ukemi',
'88. Blindfolded outside',
'89. Round of categories',
'90. Pokernight poem',
'91. Try not to laugh',
'92. Round of shots',
'93. Forced shot buddies',
'94. Tape hand and legs 10min',
'95. Who knows who',
'96. Neck tap ',
'97. New song recommendation',
'98. Say a sentence in a foreign language',
'99. Ala Habibi Resurrected ',
'100. Bet on one of the guys (W/ Drink | L/ No Drink | Shot/ Double it & Drink)',
'101. 1 Glass Shot Pong',
'102. Round of shots',
'103. New rule until the tower falls',
'104. Whos most likely to',
'105. Balancing 1v1/ last drink',
'106. Give a genuine compliment/ last dare'],

wheel_changes: [
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [
"#E74C3C",
"#7D3C98",
"#2E86C1",
"#138D75",
"#F1C40F",
"#D35400",
"#138D75",
"#F1C40F",
"#b163da",
"#E74C3C",
"#7D3C98",
"#138D75",
]

};