var json_vergi_psycho = {

dares: [
'1. Cock reveal',
'2. Hop in trash',
'3. Ice shower 20 sec / Take a swin (Lohja/Teisko)',
'4. 10 min ZERO layers',
'5. CRAZY Never have I ever NOT joka gettaa kaikki',
'6. Tug of war käsillä/ last drink',
'7. Heel to toe/ last dare',
'8. Waterboarding',
'9. Roundhouse kick',
'10. Next piece & dare blindfolded',
'11. Situps, pushups, squats 10x 15sec',
'12. Talon ympäri no pants/no shirt',
'13. Run it down luoteisväylä (no pants AND NO shirt)',
'15. Music video CYBERPUNK TYPE SONG',
'16. Lick doorknob / Match on tongue',
'17. Join the next TWO dareS',
'18. 2 mins TRAP porn',
'19. 50/50 Talon katolle TAI RUN IT DOWN',
'20. Round of shots',
'21. WhatsApp IMAGE OF YOU RN',
'22. Slap to the face',
'23. Ass slap TWO roundS',
'24. Breath holding /last dare',
'26. 1v1 kädenvääntö/ last drink',
'27. Crab walk 1V1 /LAST DARE',
'28. Dodgy accent & impression / Puhu takaperin 4 Min',
'29. Staring contest/ last drink',
'30. Shamone',
'31. Round of shots',
'33. Freestyle',
'34. Confession: idol / person you despise / wierd thing youve done alone',
'35. Three shots 1 water 2 vergi',
'37. 50/50 shot tai kaikki muut shottaa',
'40. Karaoke',
'41. REENACT THAT CASINO ROYALE SCENE (FOR REAL)',
'42. Round of shots',
'44. Bare back slap TWICE',
'46. Odds on/ last dare',
'47. Walk a straight a line / Walk the plank (Lohja/Teisko)',
'51. Geoguesser AMERICAN STATES',
'52. Round of shots',
'53. 50/50 6 pieces tai 2 shotS',
'54. Blitz round 30 SECONDS',
'56. 50/50 2 shots tai free pass',
'57. Confession: non pornstar DUDE johon oot nutannu / fictional DUDE youd bang',
'59. RPS for a shot EVERYONE',
'62. Round of shots',
'65. 1 min plank PLUS MAX PUSH UPS/ wall sit PLUS MAX SQUATS',
'67. Round of associations',
'69. Make a cocktail with onhand ingredients, choose a donnie to taste test WITH YOU',
'72. Round of shots',
'73. Categories 1v1V1V1/ last drink',
'74. Thumb war CIRCLE',
'75. Back to Back most likely to finish drink /last dare',
'76. 3 LIES 0 TRUTH',
'77. Rap battle/ call out',
'78. Show the boys a dance move',
'80. 2 free pass then forced dare',
'82. Round of shots',
'84. Dishwashing liquid 20 sec',
'87. Cartwheel, handstand JA ukemi',
'88. Blindfolded outside',
'92. Round of shots',
'93. Forced shotbuddies',
'94. Tape hand and legs AND BLINDFOLD 10min',
'96. Neck tap',
'99. Ala Habibi Resurrected',
'100. Bet on one of the guys (W/ Drink | L/ No Drink | Shot/ Double it & Drink)',
'101. 1 Glass Shot Pong',
'102. Round of shots',
'103. New rule until tower falls',
'105. Balancing 1v1/ last drink'
],

wheel_changes: [
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free'
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [
'#00ff9f',
'#00b8ff',
'#d600ff',
'#001eff',
'#bd00ff'
]

};