var json_no_enemies = {

dares: [
'1. Cock reveal',
'2. Hop in trash',
'3. Ice shower 20 sec / Take a swin (Lohja/Teisko) IN SILENCE',
'4. 10 min 3 layers',
'7. Heel to toe/ last dare',
'8. Waterboarding',
'9. Roundhouse kick',
'10. Next piece & dare blindfolded',
'11. Situps, pushups, squats 10x 15sec',
'12. Talon ympäri 20 secs',
'13. Run it down luoteisväylä (no pants/shirt)',
'15. Music video',
'16. Lick doorknob / Match on tongue',
'17. Join the next dare',
'18. 2 mins gay porn',
'19. Talon katolle',
'20. Round of shots',
'22. Slap to the face',
'23. Ass slap round',
'25. Kiss one of the boys',
'27. Crab walk',
'28. Dodgy accent & impression / Puhu takaperin 4 Min',
'30. Shamone',
'31. Round of shots',
'32. AMA',
'33. Freestyle SELF DEPRICATING',
'35. Three shots 1 water 2 vergi',
'36. 5 second challenge',
'39. Playlist quiz 5 songs',
'40. Karaoke SAD/EMOTONAL SONG',
'41. Movie scene/porn scene',
'43. Confession : HOW ARE YOU LIKE THORFINN',
'44. Bare back slap, WITH NO REACTION',
'45. Piirrä donnie 1 min',
'47. Walk a straight a line BAREFOOT, OUTSIDE/ Walk the plank (Lohja/Teisko)',
'48. Tell us something you hate about yourself BUT ARE STRIVING TO OVERCOME',
'49. Who wants to be a mentalist',
'50. Puhu NON NEGATIVELY 3 min',
'51. Geoguesser VINLAND EDITION',
'52. Round of shots',
'53. 50/50 3 pieces tai shot',
'54. Blitz round 1 min',
'55. EXPLAIN YOUR IDENTITY / EXPLAIN YOUR RELIGION',
'56. 50/50 2 shots tai pain dare of your choice',
'57. Confession: non pornstar johon oot nutannu / fictional character youd bang',
'58. Confession: kink / favourite porn plot / most or least favourite cliche / favourite porn video',
'61. Original INSPIRATIONAL refrence',
'63. Secret banned category',
'64. Charades WITHOUT BEING OFFENSIVE (15 correct in custom)',
'65. 1,5 min plank / wall sit',
'66. Draw a 3 panel comic ABOUT HOW YOU HAVE NO ENEMIES',
'67. Round of associations',
'68. Round of rhymes',
'69. Make a cocktail with onhand ingredients, OFFER YOURSELF TO TASTE',
'70. Spelling bee SWE NOR DAN',
'71. Descriptions',
'72. Round of shots',
'76. 3 truths 0 lie',
'78. Show the boys a dance move',
'79. Minkä fictional characterin elämäst OOT PROUD / minkä fictional characterin kanssa voisit olla friends',
'80. FREE PASS FOR YOU AND ANOTHER OF YOUR CHOICE then forced dare FOR YOU ONLY',
'81. Association test',
'83. Confession: bad person moment JOSTA LEARNASIT / WHOLSOME THING thing / spirit animal',
'84. Dishwashing liquid 20 sec',
'85. Tongue twister',
'86. OFFERAA SUN HOUSUT (YOU DONT NEED THEM) 10m/ last drink',
'87. Cartwheel / handstand / ukemi',
'88. Blindfolded outside',
'89. Round of categories',
'90. Pokernight poem ABOUT NO ENEMIES',
'91. Try not to laugh',
'92. Round of shots',
'93. Forced shotbuddies WITH YOURSELF',
'94. Tape hand and legs 15min',
'95. Who knows who',
'96. Neck tap',
'97. New song recommendation JOKA MEANAA SOMETHING TO YOU',
'98. Say a sentence in a SCANDINAVIAN language',
'101. 1 Glass Shot Pong',
'102. Round of shots',
'103. New rule until tower falls',
'104. Whos most likely to',
'106. Give a genuine compliment AND HUG/ last dare'
],

wheel_changes: [
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : Box of Memes',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho'
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 1 layer (4 pieces)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Double Up (all save shots are x2)',
'ENVIRONMENT : Firm it, no chasers (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiplies and rerolls',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [
'#41543F',
'#B8C645',
'#78AC23',
'#B8C795',
'#866045'
]

};