var json_memes = {

dares: [
'1. Cock reveal',
'2. Hop in trash',
'3. Ice shower 20 sec',
'5. Never have I ever joka gettaa kaikki',
'6. Tug of war käsillä/ last drink',
'7. Heel to toe/ last dare',
'8. Waterboarding',
'9. Roundhouse kick',
'10. Next piece & dare blindfolded',
'13. Run it down luoteisväylä (no pants/shirt)+(chainsaw)+(jouluhattu)',
'14. Meme noises',
'15. Meme video ',
'16. Lick doorknob / Match on tongue',
'17. Join the next dare',
'18. 2 mins gay porn',
'19. Talon katolle? + jump',
'20. Round of shots',
'21. WhatsApp send a meme ',
'23. Ass slap round + noise',
'25. Kiss one of the boys lips',
'26. 1v1 kädenvääntö both hands/ last drink',
'27. Crab walk (reverse)',
'28. Dodgy meme accent & impression / Puhu memeillä 4 Min',
'29. THOUSAND YARD Staring contest/ last drink',
'30. Shamone',
'31. Round of shots',
'32. AMA',
'33. Freestyle MEME BEAT',
'34. 10 second, Roe Jogan challenge, 3 impressions ',
'35. Three shots 1 water 2 vergi',
'36. 5 second challenge memes',
'37. 50/50 shot tai kaikki muut shottaa',
'38. Unkown meme refrence',
'39. Playlist quiz 5 songs',
'40. Karaoke (freebird)',
'41. Movie scene/meme scene',
'42. Round of shots',
'43. Confession : journal page / journal page / journal page / journal page',
'44. Bare back slap',
'45. Piirrä MEME 1 min',
'46. Odds on/ last dare (cant be greater than 1/3)',
'47. Walk a straight a line (hands & feet)',
'48. Tell us something you hate about youself / Narcissim 3 things 5 sec',
'49. Who wants to be a mentalist MEME EDITION',
'50. Puhu refrenceillä 3 min',
'51. Geoguesser',
'52. Round of shots',
'53. 50/50 3 pieces tai shot',
'54. Blitz round 1 min',
'55. Sell me this',
'56. 50/50 2 shots tai free pass',
'57. Confession: memepornstar johon oot nutannu / meme character youd bang',
'58. Confession: FAVOURITE MEME VIDEO',
'59. RPS for a shot anyone',
'60. New good dare in 2 mins',
'61. Original refrence',
'62. Round of shots',
'63. Secret banned category',
'64. Charades',
'65. 1 min plank / wall sit naked (while waterboarded)',
'66. Draw a 3 panel meme',
'67. Round of associations',
'68. Round of rhymes',
'69. Make a cocktail with onhand ingredients, choose a donnie to taste test',
'70. Spelling bee CHI RUSS PORT',
'71. Descriptions (memes)',
'72. Round of shots',
'73. Categories 1v1/ last drink',
'74. Thumb war with an ally against teo/ last drink',
'75. Radio groups quiz',
'76. 1 truth 1 lie ',
'77. Rap battle/ call out',
'78. Show the boys a dance move (meme)',
'79. Minkä meme characterin elämän haluaisit / minkä meme characterin kanssa voisit olla friends',
'80. 2 free pass then forced dare',
'81. Association test',
'82. Round of shots',
'83. Confession: pervy thing / pervy thing / pervy thing',
'84. Dishwashing liquid 20 sec',
'85. Tongue twister',
'86. Vaihda fittiä HEARBURN 10m/ last drink',
'87. ukemi / ukemi / ukemi',
'88. Blindfolded outside (infamous house)',
'89. Round of memes',
'90. Pokernight poem (arabic)',
'91. Try not to laugh (shitty meme editions)',
'92. Round of shots',
'93. Forced shotbuddies',
'94. Tape hand, legs & mouth 10min',
'95. Who knows who (meme edition poggers!)',
'96. Neck lick BUCCARATI',
'97. New song recommendation (must be from a meme)',
'98. Say a sentance in arabic',
'99. Ala Habibi Resurrected ONE HAND BEHIND BACK',
'100. 1 Glass Shot Pong',
'101. ROund of Shots',
'102. New Rule until tower falls',
'103. Whos most likely to'
],

wheel_changes: [
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : I have no enemies',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : No Sitting',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Pain Free',
'WHEEL CHANGE : Vergipsycho',
'WHEEL CHANGE : Vergipsycho'
],

environments: [
'ENVIRONMENT : All dice rolls except 0 are 4 pieces(one layer)',
'ENVIRONMENT : All dice rolls except 0 are 4 pieces(one layer)',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Choose a Themed Wheel to swap into',
'ENVIRONMENT : Double up all shots until for a cycle',
'ENVIRONMENT : Double up all shots until for a cycle',
'ENVIRONMENT : No chasers allowed, firm it (shot sizes can be smaller)',
'ENVIRONMENT : No chasers allowed, firm it (shot sizes can be smaller)',
'ENVIRONMENT : Round of Shots multiply and reroll',
'ENVIRONMENT : Round of Shots multiply and reroll',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Team Jenga',
'ENVIRONMENT : Disable one Themed Wheel',
'ENVIRONMENT : Disable one Themed Wheel',
],

colors: [
'#f00c0c',
'#212fcd',
'#d62d2d',
'#2bdc4c'
]

};